### ISSUE TITLE
Docs for quoted-string missing

### ISSUE THREAD

**Issue by adamchainz** [adrienverge/yamllint#137]
Upgrading to version 1.12.0, I see there's a new rule `quoted-string` in the changelog, but it doesn't appear in the docs at: https://yamllint.readthedocs.io/en/stable/rules.html . Perhaps the docs build is broken - I've experienced docs builds failing silently on readthedocs before.

**Comment by adrienverge** [comment]
It's because PR https://github.com/adrienverge/yamllint/pull/130 by @mgmgwi didn't add this rule to documentation. I fixed it in https://github.com/adrienverge/yamllint/commit/e864f57, so it will be included in the next *stable* release. In the meantime, the documentation for `quoted-string` is available at https://yamllint.readthedocs.io/en/latest/rules.html

Sorry about the inconvenience!
