### ISSUE TITLE
Make FILE_OR_DIR argument optional

### ISSUE THREAD

**Issue by ssbarnea** [adrienverge/yamllint#213]
I would like to propose making `yamllint` easier to run by not requiring file/dir arguments, defaulting to the first folder containing the `.yamllint` file. This behavior is already common among other linters like `flake8`, `pep8` or `ansible-lint`.

If the detection of yamllint config file worry you, we could make CWD implicit default as for most cases it will be the same, so `yamllint .` would be the same as `yamlint`, in fact much easier to implement.

**Comment by kjetilho** [comment]
relying on a `.yamllint` to exist is a bad heuristic.  also very strange if you happen to be in / when you write yamllint - "why is my laptop getting hot?" while it is doing an initial pass through your filesystem, looking and looking for `.yamllint`.

however, making "." the default FILE_OR_DIR sounds fine to me.  if it is good enough for ls(1), it should be good enough for yamllint ;)

**Comment by adrienverge** [comment]
Hey, why not!

> if it is good enough for ls(1), it should be good enough for yamllint

Good point :slightly_smiling_face:
But for some other UNIX programs, absence of `FILE` arguments means "*read from standard input*". Since version 1.15.0, yamllint can read from stdin, but needs an extra argument (`yamllint -`). So, "*making . the default FILE_OR_DIR*" seems possible without coherence problem.

However, yes I'd prefer looking for `.yamllint` only in current working directory; it could confuse users otherwise.
