### ISSUE TITLE
Indentation of lists

### ISSUE THREAD

**Issue by mboehm21** [adrienverge/yamllint#268]
Hi,

in an Ansible-training they told me to use the following indentation for lists:

```
just_a_dict:
  whatever: false
just_a_list:
 - element_1
 - element_2
```

I used this syntax in many roles and would like to keep it that way. How can I tell yamllint to accept ` - ` without switching the identation-check off entirely?

Thanks a lot.

**Comment by adrienverge** [comment]
Hello,

You want to have **2 spaces** for dicts, and **1 space** for lists, right?

yamllint rule `indentation` tries to enforce a *consistent indentation*, which means you can't use this rule to check custom mixed indentations values like this, I'm afraid.

**Comment by ssbarnea** [comment]
Wow! I am happy to discover that I am not the only person trying to find a way to consolidate the formatting of sequences (lists) on YAML. I started writing an article about the subject because it is what I would call the pandora-box of YAML formatting, as there are two big trends manifesting around, both of them very strong in their beliefs: `no indentation` and `2 char indentation` matching those of maps.

Clearly what @mboehm21 proposed is not popular and has no changes to become adopted, mainly because it breaks the indentation as being a multiplier of base indent (2, 4, 6,..).

Consistent was a great idea and probably should still be the default for a long time, at least until we manage to get some community consensus between the two others.

**Comment by mboehm21** [comment]
Hey @adrienverge, @ssbarnea, thanks for your answers.

So I read in your comments that the style I got taught and adopted is uncommon. It probably was just the personal preference of the Ansible-teacher I had in the workshops.

Did I get that correctly? Then I'll rework my lists in the Ansible-files to "space space dash space" and we can close the issue.

**Comment by adrienverge** [comment]
@mboehm21 that's it. Your style is perfectly valid, but uncommon. If you want yamllint to enforce the `indentation` rule on your files, using either "space space dash space" or "dash space" should work :+1:

**Comment by mboehm21** [comment]
Thanks for your work on this project and quick help with my issue. I'll close it.
