### ISSUE TITLE
Conflicting values between `empty-lines` and `new-line-at-end-of-file`

### ISSUE THREAD

**Issue by rEnr3n** [adrienverge/yamllint#403]
Note: No config file is created by me.
```
$ yamllint --version
yamllint 1.26.3
```
```
$ cat test.yaml 
---
name: test

```
```
$ yamllint .
./test.yaml
  3:1       error    too many blank lines (1 > 0)  (empty-lines)

```

Docs say `empty-lines` and `new-line-at-end-of-file` are enabled by default. The default values for `empty-lines` are:
```
rules:
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
```
The `max-end` here seems to be in conflict with `new-line-at-end-of-file`. Shouldn't the default value of `max-end` be 1 instead of 0?

**Comment by adrienverge** [comment]
Hello,

Given your example:
```
---↵
name: test↵
↵
```
there are:
- 2 new line characters at the end of your file (see the `↵` I inserted). You can see this by inspecting the file as binary.
- 1 empty line.

The rule `new-line-at-end-of-file` requires 1 new line character the end, so it should be:
```
---↵
name: test↵
```
This last example satisfies both `new-line-at-end-of-file: enabled` and `empty-lines: {max-end: 0}`.

Maybe your confusion was because numbers 2, 0 and 0 in `empty-lines` are about *empty lines*, while `new-line-at-end-of-file` is about the *new line character* `\n`?

I'll close this, but feel free to reopen if needed.

**Comment by rEnr3n** [comment]
> Maybe your confusion was because numbers 2, 0 and 0 in `empty-lines` are about _empty lines_, while `new-line-at-end-of-file` is about the _new line character_ `\n`?

Yeah I guess. I thought this:
```
---
name: test
```
looked like this:
```
---↵
name: test
```

I've read about issues regarding not having new line at the end of the file. So I assumed I had to insert an empty line at the end. Are they perhaps issues regarding the old softwares?

---
On the other hand, I don't know if this is related but after I created this config the same file on OP does not get an error anymore.
```
---

rules:
  line-length:
    allow-non-breakable-inline-mappings: true
```
