### ISSUE TITLE
automatic format

### ISSUE THREAD

**Issue by Huarong** [adrienverge/yamllint#62]
Hope this tool can format the code automatic, just like `yapf -i` for Python.

**Comment by adrienverge** [comment]
No sorry, it doesn't. yamllint is only a linter: it reports potential problems but doesn't fix them (mainly because there could be ambiguities in fixing).

**Comment by adius** [comment]
This would be really great. If the warning is that there is a trailing newline missing, it would be really easy to fix ;-)

**Comment by adius** [comment]
Tools like ESlint also only provide auto fixing for a subset or rules...

**Comment by zanona** [comment]
`yamlint --fix` would indeed be great. Not all errors would have support for fixing, just as eslint but at least a few of them like, adding `---` on beginning of files, etc.

**Comment by jayvdb** [comment]
Building a new auto-fixing tool around yamllint would be a good approach for anyone wanting this.

e.g. autoflake wraps pyflakes, and autopep8 wraps pycodestyle.

Where the linter doesnt expose enough information to aide fixing, that is a valid problem with the linter.

**Comment by jayvdb** [comment]
It is probably worthwhile adding a note to the readme that reformatting is out of scope.

Maybe include some recommendations on existing Python yaml reformatters , and non-Python ones (jq?), which support the yamllint default style.

The jq wrappers for python are probably the best options IMO , but yq has a problem with indentation https://github.com/kislyuk/yq/issues/52 .

At https://stackoverflow.com/questions/30642317/how-to-automatically-re-indent-a-yaml-file  , @ruamel recommends his `ruamel.yaml.cmd` which utilises his now well recognised `ruamel.yaml` library - but then I run into https://bitbucket.org/ruamel/yaml.cmd/issues/4/stack-trace-when-using-save-patch-linked 

https://github.com/dbohdan/remarshal is popular, and could be used to convert yaml2toml , and then toml2yaml , however note indentation is an issue there too https://github.com/dbohdan/remarshal/issues/13 .

Hmm..

**Comment by jayvdb** [comment]
https://github.com/mk-fg/pretty-yaml works for several files I've tried, and has very basic cli.

`$ python -m pyaml /path/to/some/file.yaml`

**Comment by jayvdb** [comment]
@ruamel fixed and released a new version of https://pypi.org/project/ruamel.yaml.cmd/ , and I've packaged it for openSUSE https://build.opensuse.org/project/show/home:jayvdb:ruamel

It prefers single quotes over double quotes, and likes `\` line continuations within quoted strings, but it does do indents nicely.

**Comment by dudicoco** [comment]
I've been breaking my head over finding a formatter that would provide more or less the same features as yamllint via cli or via VSS, i've already tried all of the suggestions mentioned here.

Can someone suggest a tool that would provide formatting similar to the following rules in yamllint:
```
rules:
  colons: enable
  empty-lines:
    max: 1
  empty-values: enable
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: false
  key-duplicates: enable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  trailing-spaces: enable
```

Thanks!

**Comment by adrienverge** [comment]
Hey @yvele,

I agree such a feature would be great. It could be in a separated command like `yamlfix`.

Would you want to implement and maintain this?

Here are the 4 main issues I see:
1. The fix feature would apply unquestionably for some rules (ones about whitespaces).
   But as you point out, for other rules there would be ambiguity. Still, users will want us to fix them anyway (with they would reasonably be right).
2. There would also be *inter-rules* ambiguities. For example, a badly-indented key-value pair would be reindented to the next level, while the user wanted it at the previous (parent) level.
3. Fixing code while respecting rules options (like `ignore-shebangs`, `indent-sequences: consistent`, etc.) is a real challenge.
4. Based on my experience, creating + maintaining such a tool would be much more work than for `yamllint` itself.
   Moreover, if there's a bug in yamllint, it's OK. But if there's a bug in a tool that *modifies* users files, you have to be extra careful and reactive to fix bugs, because you could be blamed for ruining users work.

**Comment by dudicoco** [comment]
My solution was to use yamllint with `pre-commit` together with the `yamlfmt` hook: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt

**Comment by tamere-allo-peter** [comment]
FYI another fixer with a different approach : https://github.com/opt-nc/yamlfixer

**Comment by oussjarrousse** [comment]
Why not combine efforts with one of the yamlfix projects to provide both checking and fixing functionality?

**Comment by RukshanJS** [comment]
> Just FYI https://github.com/lyz-code/yamlfix

Tested, works perfectly. Thanks a bunch!

**Comment by socherbyc** [comment]
Man, this `yamlfix` broke many of my yaml files. For example, it changes
```yaml
  example: 'foo #bar'
```

to
```yaml
  example: 'foo # bar'
```

I just can't use it :/

**Comment by andrewimeson** [comment]
@socherbyc - wrong repo, old closed issue. This is yamllint, not yamlfix.
