### ISSUE TITLE
AttributeError: module 'yamllint' has no attribute 'config'/'linter'

### ISSUE THREAD

**Issue by jamesquilty** [adrienverge/yamllint#698]
The example code in the [Development](https://yamllint.readthedocs.io/en/stable/development.html) documentation page throws an error for me with yamllint 1.35.1 running on Python 3.12:

```text
$ python3
Python 3.12.4 (main, Jul 13 2024, 16:37:48) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yamllint
>>> yaml_config = yamllint.config.YamlLintConfig("extends: default")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'yamllint' has no attribute 'config'
```

it will work if I amend the import statement:

```python
>>> from yamllint.config import YamlLintConfig
>>> yaml_config = YamlLintConfig("extends: default")
>>> yaml_config
<yamllint.config.YamlLintConfig object at 0x1033d8710>
```

The documentation seems Pythonic, so perhaps there's a misconfiguration somewhere?

**Comment by adrienverge** [comment]
Hello and thanks for the report!

That's true, I confirm this inconsistency in [the development section of documentation](https://yamllint.readthedocs.io/en/v1.35.1/development.html). It has been the case since 2016 and commit dbbecb5 (just after yamllint was created) to solve another problem.

I propose to fix the documentation to use `import yamllint.config` instead of `import yamllint`: https://github.com/adrienverge/yamllint/pull/699.
